### PR TITLE
Adding Foundation template

### PR DESCRIPTION
**Pull request by stackrole-dev**
**- Summary**
Adding Foundation Gatsby and NetlifyCMS starter
Github: https://github.com/stackrole/gatsby-starter-foundation

**- Test plan**
Demo: https://foundation.stackrole.com/

**- Description for the changelog**
Adding new a template

### CODE REVIEW

**Comment by stackrole-dev** [comment]
Hi Netlify,

When i can expect this to be merged.

Thank you

**Comment by stackrole-dev** [comment]
Hi @philhawksworth,

Did not new who to tag, so tagging you here. When can i expect my starter be added to Netlify

**Comment by philhawksworth** [comment]
Merged.
Thanks a lot @stackrole-dev!

**Comment by stackrole-dev** [comment]
Thank you @philhawksworth waited very long for this ☺️

**Pull request merged**
