### PR TITLE
PlanetScale Next.js Starter App

### PR DESCRIPTION
**Pull request by tbarn**
**- Summary**

There were few Next.js templates on the sites, as well as few templates that used any authentication. This starter app helps a developer get started with both and sees an example of using serverless databases in a Jamstack app. 

Note: We are working on even better documentation for this outside of the readme in the next couple of days, but I didn't want to wait too long to get this PR in. 

**- Description for the changelog**

A new Next.js starter app that uses NextAuth.js and PlanetScale serverless databases

### CODE REVIEW

**Comment by maxcell** [comment]
Howdy @tbarn!

I appreciate you opening the PR! I caught one thing where the template file your adding is missing an extension, can you make sure to add a `.md` because that will help make sure that Eleventy processes it correctly. If you currently try to go to the Deploy Preview from the bot, you notice that the starter doesn't even pop up 😱

**Comment by tbarn** [comment]
oof, my bad @maxcell! I should definitely make a file that I wrote with Markdown a `.md` file.

**Comment by tbarn** [comment]
@maxcell Is there a way to retrigger the build so I can make sure I set up everything correctly? thank you!

**Review by maxcell — APPROVED** [review]
Everything looks good to me! Thank you for submitting this! 😄

**Pull request merged**
