### PR TITLE
Added Bael Template

### PR DESCRIPTION
**Pull request by jake-101**
**- Summary**

I think that my template will be a good addition to the Netlify Template directory.

**- Test plan**

I did a test deploy to Gitlab and it worked.

**- Description for the changelog**

Added Bael Blog Template .md and preview image

### CODE REVIEW

**Comment by philhawksworth** [comment]
This is great! Thanks for this contribution @jake-101 !

Some of the image assets are rather large. I wonder if it might be possible to compress those a little in the source (I don't think I saw a build step to optimise them, which is all good, but it would be nice if we could squeeze the originals a little).

I'd also exclude the dist folder from the repo by adding it to `.gitignore`

With those small changes, I'd eagerly accept this PR. Thanks indeed!

**Comment by philhawksworth** [comment]
(Preview: https://deploy-preview-13--templates.netlify.com/template/nuxt-bael-blog-template/)

**Comment by jake-101** [comment]
Hi Phil, thanks for the recommendations. I don't have a build step to create smaller images but I will resize the ones that I do include or maybe host them remotely. I am going to put in pagination too and let you know here when I have the changes made. I will make an ecommerce JAMstack template next!

**Comment by philhawksworth** [comment]
No need to host the images remotely, better really to keep this self-contained if possible. But perhaps squeezing them a little using ImageOptim or similar would be a good idea.

**Comment by jake-101** [comment]
Hi Phil, I went ahead and made the changes requested. I took out unused images, removed the dist folder, ran imageoptim on everything, and added pagination.

**Comment by philhawksworth** [comment]
Thanks @jake-101 !
I've cleaned up the tags a tiny bit so that tags on this site are mostly focussed on the technology and features being used.

Merged.

Many thanks for the contribution!

**Pull request merged**
