### PR TITLE
Update PHPoole/Cecil

### PR DESCRIPTION
**Pull request by Narno**
Cecil is now a "simple" starter blog and PHPoole is now Cecil! \o/

### CODE REVIEW

**Comment by philhawksworth** [comment]
Netlify is preparing a preview build of this PR

Built with commit c6eee2db46826b1647f47d667a977015042d8a45

https://app.netlify.com/sites/templates/deploys/5bd73b49fdd72a4a0393410e

**Comment by Narno** [comment]
Poke @philhawksworth :wave:

**Comment by Narno** [comment]
Poke @philhawksworth :wave:

**Comment by Narno** [comment]
Poke @philhawksworth :wave:

**Comment by Narno** [comment]
Anybody there? :-/

**Comment by erquhart** [comment]
@Narno sorry for the wait on this, thanks for the update!

**Comment by Narno** [comment]
Yeah, thanks a lot @erquhart! 😗

**Pull request merged**
